In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

In [2]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

In [9]:
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""
    Line 1
    Line 2
    Line 3
    """)
    
    ds_file = tf.data.TextLineDataset(filename)

In [11]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [12]:
print('Elements of ds_tensors:')
for x in ds_tensors:
    print(x)

print('\nElements in ds_file:')
for x in ds_file:
    print(x)

Elements of ds_tensors:
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([ 9 36], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'' b'    Line 1'], shape=(2,), dtype=string)
tf.Tensor([b'    Line 2' b'    Line 3'], shape=(2,), dtype=string)
tf.Tensor([b'    '], shape=(1,), dtype=string)
